version: '{build}'
os: Visual Studio 2019
configuration: Release
platform: x64

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

branches:
  except:
    - coverity_scan # No need for Windows builds on that branch

skip_commits:
  message: /\[(skip ci)|(ci skip)\]/

cache: c:\tools\vcpkg\installed -> appveyor64.yml

install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%

before_build:
- cmd: |
    echo Installing dependencies...
    vcpkg integrate install
    vcpkg install boost-date-time:x64-windows
    vcpkg install boost-filesystem:x64-windows
    vcpkg install boost-format:x64-windows
    vcpkg install boost-locale:x64-windows
    vcpkg install boost-optional:x64-windows
    vcpkg install boost-system:x64-windows
    vcpkg install curl:x64-windows
    vcpkg install --recurse freetype:x64-windows
    vcpkg install glew:x64-windows
    vcpkg install libraqm:x64-windows
    vcpkg install sdl2:x64-windows
    vcpkg install sdl2-image[libjpeg-turbo]:x64-windows
    git submodule update --init --recursive
    echo Running cmake ..
    cmake -G "Visual Studio 16 2019" -A x64 -DVCPKG_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=%P% -DHAVE_SDL=true -DPACKAGE_VCREDIST=true %APPVEYOR_BUILD_FOLDER%

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

after_build:
- cmd: '"C:\Program Files (x86)\CMake\bin\cpack.exe"'

test: off 

artifacts:
- path: st_launcher*
  name: setup

